"""
Generate the cross-language golden contract: shared/test_vectors.json

Runs the canonical Python `analyse()` over deterministic synthetic weekly-close
series that exercise every branch of the maths, and records (input, params,
expected output). The TypeScript port loads the SAME file and must reproduce
every expected value. This is the single source of truth that keeps the two
implementations identical.

Run:  python/.venv/bin/python python/gen_test_vectors.py
"""
import json
import os

import numpy as np
import pandas as pd

from wma200_scanner import WEEKS, analyse

OUT = os.path.join(os.path.dirname(__file__), "..", "shared", "test_vectors.json")

rng = np.random.default_rng(42)
IDX = pd.date_range(end="2026-07-03", periods=320, freq="W-FRI")


def gbm(start, drift, vol):
    r = rng.normal(drift, vol, len(IDX))
    return pd.Series(start * np.exp(np.cumsum(r)), index=IDX)


def build_cases():
    cases = []

    # CROSSED DOWN: uptrend whose final week breaks below a rising MA
    down = gbm(50, 0.004, 0.03)
    ma_d = down.rolling(WEEKS).mean().iloc[-1]
    down.iloc[-2], down.iloc[-1] = ma_d * 1.04, ma_d * 0.93
    cases.append(("crossed_down", down, 10.0, 0.0))

    # CROSSED UP: long base whose final week pops above the MA
    up = gbm(100, 0.0005, 0.02)
    ma_u = up.rolling(WEEKS).mean().iloc[-1]
    up.iloc[-2], up.iloc[-1] = ma_u * 0.97, ma_u * 1.06
    cases.append(("crossed_up", up, 10.0, 0.0))

    # NEAR (above): sits just above its MA, inside the band, no cross
    near_a = gbm(30, 0.001, 0.015)
    ma_na = near_a.rolling(WEEKS).mean().iloc[-1]
    near_a.iloc[-2], near_a.iloc[-1] = ma_na * 1.02, ma_na * 1.03
    cases.append(("near_above", near_a, 10.0, 0.0))

    # NEAR (below): sits just below its MA, inside the band, no cross
    near_b = gbm(40, 0.001, 0.015)
    ma_nb = near_b.rolling(WEEKS).mean().iloc[-1]
    near_b.iloc[-2], near_b.iloc[-1] = ma_nb * 0.98, ma_nb * 0.97
    cases.append(("near_below", near_b, 10.0, 0.0))

    # FAR / breadth-only: way above its MA, outside the band -> {"above": True}
    far = gbm(20, 0.006, 0.02)
    cases.append(("breadth_only_above", far, 10.0, 0.0))

    # TOO SHORT: fewer than WEEKS + 14 bars -> None
    short = pd.Series(
        np.linspace(10, 20, WEEKS),          # only 200 bars < 214 required
        index=pd.date_range(end="2026-07-03", periods=WEEKS, freq="W-FRI"),
    )
    cases.append(("too_short", short, 10.0, 0.0))

    # BELOW MIN PRICE: would otherwise be NEAR, but price_now < min_price -> None
    cheap = near_a.copy()
    cases.append(("below_min_price", cheap, 10.0, 1e9))

    return cases


def serialise_series(s: pd.Series):
    return [[d.strftime("%Y-%m-%d"), float(v)] for d, v in s.items()]


def main():
    vectors = []
    for name, series, band, min_price in build_cases():
        expected = analyse(series, band, min_price)
        vectors.append({
            "name": name,
            "band_pct": band,
            "min_price": min_price,
            "closes": serialise_series(series),
            "expected": expected,   # None | {"above": bool} | full signal dict
        })

    payload = {
        "_note": "Golden contract generated by python/gen_test_vectors.py. "
                 "The TypeScript port must reproduce every 'expected' value. "
                 "Numeric fields compared with tolerance (Python uses "
                 "round-half-to-even; JS Math.round differs on exact halves).",
        "weeks": WEEKS,
        "vectors": vectors,
    }
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w") as f:
        json.dump(payload, f, indent=2)

    summary = {v["name"]: (v["expected"]["signal"] if isinstance(v["expected"], dict)
                           and "signal" in v["expected"]
                           else v["expected"]) for v in vectors}
    print(f"Wrote {os.path.relpath(OUT)} with {len(vectors)} vectors:")
    for k, val in summary.items():
        print(f"  {k:20} -> {val}")


if __name__ == "__main__":
    main()
